# This is a basic workflow to help you get started with Actions

name: py-eodms-rapi Tests

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'development'

      # List files
      - name: List files
        run: ls
      
      # Install package from setup.py
      - name: Install package from setup.py
        run: |
          sudo python setup.py install

      # Runs a single command using the runners shell
      - name: Run py-eodms-rapi Test 1 - Search, Order & Download
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.USERNAME }}
          EODMS_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          cd test
          python -m unittest test_pyeodmsrapi.TestEodmsRapi.test_search
          
      # Runs a single command using the runners shell
      - name: Run py-eodms-rapi Test 2 - Show Order Parameters
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.USERNAME }}
          EODMS_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          cd test
          python -m unittest test_pyeodmsrapi.TestEodmsRapi.test_orderparameters
          
      # Runs a single command using the runners shell
      - name: Run py-eodms-rapi Test 3 - Delete Order
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.USERNAME }}
          EODMS_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          cd test
          python -m unittest test_pyeodmsrapi.TestEodmsRapi.test_deleteorder
          
      # Runs a single command using the runners shell
      - name: Run py-eodms-rapi Test 4 - Get Available Fields
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.USERNAME }}
          EODMS_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          cd test
          python -m unittest test_pyeodmsrapi.TestEodmsRapi.test_availablefields
